### ISSUE TITLE
Font does not scale up or down

### ISSUE THREAD

**Issue by phil-andrews** [diogofilipee/brackets-macos-xcode-dusk#1]
Love this theme as I'm so used to it in Xcode. Unfortunately the font for this theme does not seem to support scaling.
Release 1.7 build 1.7.0-16898 (release b0a363b71)

**Comment by diogofilipee** [comment]
Nice!

No doesn't scale, it's true because in theme.css have in line 35 this
**font-size: 11px !important;**

Now with the upgrade of Xcode yes I have to change font-size but before, the font-size, was 11px. And Xcode Dusk Theme will be called Xcode Civic Theme. Im working on that!

Thank you for your feedback!
Best regards diogofilipee
